### ISSUE TITLE
Add username to introspection response

### ISSUE THREAD

**Issue by skeltonm** [panva/node-oidc-provider#399] opened 2018-11-16 15:33 UTC
**Is your feature request related to a problem? Please describe.**
We are setting up a resource server that will be provided with an access token that will validate the access token agains the IdP token introspection endpoint.  We need to know the identity of the user, but the resource server does not have access to the database that the sub is stored in.  Thus, we would like to add a user identifier to the token introspection endpoint so we can detect who the user is requesting the protected resource.

**Describe the solution you'd like**
The OAuth 2.0 specification defines an optional username parameter in the token introspection response ([specification](https://tools.ietf.org/html/rfc7662#section-2.2)).  We believe this could be added to the introspection response if the user has a username.  This could also be toggled by a feature flag.

**Describe alternatives you've considered**
We have considered adding the `id_token` to the request to the resource server, but there is no guarantee that the `id_token` would have the required claim data that is required by the resource server.  For instance, if a user performs an authentication request with only the `oidc` scope, the `id_token` will not contain any identity data like email or username, but only the sub, which again does not work in our situation.

**Additional context**

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment] 2018-11-16 15:42
Hi @skeltonm,

you may enrich the success json introspection response with anything you want using a custom post-middleware.

```js
provider.use(async (ctx, next) => {
  await next();
  if (
    ctx.method === 'POST' 
    && ctx.oidc.route === 'introspection' 
    && ctx.status === 200
    && ctx.oidc.entities.AccessToken
  ) {
    const { accountId: sub } = ctx.oidc.entities.AccessToken;
    const bar = await foo(sub);
    ctx.body.foo = bar;
  }
});
```

Makes sense? I think there's no need for a new feature.

**Comment by panva** [comment] 2018-11-16 15:47
Also, a dupe of #261

**Comment by skeltonm** [comment] 2018-11-16 15:54
Thanks for the info.  I had seen the other issue that was opened, but I was assuming since the username response parameter is an optional parameter of the OAuth 2.0 spec, it would be more core to the OIDC Provider than adding a custom middleware function.

Is there a reason why it shouldn't be made more core functionality?

**Comment by panva** [comment] 2018-11-16 15:57
> Is there a reason why it shouldn't be made more core functionality?

There is, since claims outside of `sub` are completely implementation specific and OIDC doesn't even standardize the `username` claim (but `preferred_username`) AND, the big one I'd like to keep introspection endpoint lightweight so that it doesn't need to load the user at all.

**Comment by skeltonm** [comment] 2018-11-16 15:58
Sounds good.  Thanks for the explanation!

**Closed by panva** 2018-11-16 15:57 UTC
Labels: question
