### ISSUE TITLE
POST to token endpoint results in 504

### ISSUE THREAD

**Issue by jpreese** [panva/node-oidc-provider#22] opened 2016-09-09 19:16 UTC
When posting to the /token endpoint, a 504 (timeout) is always being returned.  Are you aware of any potential configurations that could cause this or is this a known issue?

**Comment by panva** [comment] 2016-09-10 07:03
None of the errors in oidc-provider explicitly result in 504 response code, i would assume then these come directly from your upstream server (heroku router, nginx, apache). The cause for long requests can be either
- your adapter "hanging" (most likely) or maybe just not resolving/rejecting the methods properly (try with the default memory one if the problem persists, obviously with only one worker running)
- another reason (but unlikely one) could be your client is set to use private_key_jwt and your `timeouts.jwks_uri` configuration allows them

**Comment by panva** [comment] 2016-09-10 07:05
FYI you can use a client against the heroku deployment of the latest stable master of oidc-provider

- configuration: https://guarded-cliffs-8635.herokuapp.com/op/.well-known/openid-configuration
- various client presets: https://tranquil-reef-95185.herokuapp.com

**Closed** 2016-09-14 18:47 UTC
Labels: question, waiting for feedback

**Comment by AlexeyGrishin** [comment] 2016-12-09 12:09
@jpreese, I met same problem right now. In my case there is some conflict between express `bodyParser` and Koa `bodyParser` used inside oidc-provider. If you add express' bodyParser at application level, like this:
```javascript
app.use(bodyParser.urlencoded());
```

then you probably see this issue. I've resolved it by adding bodyParser for specific routes only, like that:
```javascript
app.post("/interaction/:grant", bodyParser.urlencoded(), (req,res) => {
    //..
});
```

Hope that helps.

**Comment by panva** [comment] 2016-12-09 12:21
Interesting, i will double check how the OP behaves when there's a body parser in upstream that already pre-parsed the body. 

Probably will do the same as in #36 and remove the dependency on a general koa-body parser. Truth be told i need to actually use the package with express myself to find out these issues.

**Comment by patrickmichalina** [comment] 2017-09-21 13:13
I used this little bit to only apply express body parse to my api:

```js
app.use('/api/**', bodyParser.json())
app.use('/api/**', bodyParser.urlencoded({ extended: false }))
```
