### ISSUE TITLE
Checks function calling db

### ISSUE THREAD

**Issue by DarkSorrow** [panva/node-oidc-provider#496] opened 2019-07-15 16:14 UTC
Hello,

I'm trying to make some queries in my database in the check i used and using the index position to make sure the query i do fill data i pass in the check
Here is an example:
`module.exports = () => new Check('client_not_authorized', 'client not authorized for End-User session yet', 'interaction_required', async (ctx) => {
   const dbGlobalConsent = await account.findConsentByEntity(
        ctx, oidc.session.account,
        oidc.entities.Client.legal_entity_id,
      );
}
`

The problem i'm running into is that it seems the checked are not waiting for the function to finish and process the other checks for this prompt. Is this an intended behaviour?
I know i could make the queries in the interaction routes but i would just like to know if it is something intended or its me who did something wrong :x

**Comment by panva** [comment] 2019-07-15 16:36
Yes, the checks run in parallel by design, but they are [awaited](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/authorization/interactions.js#L25).

**Comment by panva** [comment] 2019-07-15 16:45
You can register a non-requestable Prompt instance that runs before consent that never resolves true but does your db data loading, exposing it to your other checks e.g. via assigning to ctx.

**Comment by DarkSorrow** [comment] 2019-07-15 18:11
Thank you for the answer, i can't try it right now but i'll check tomorrow.
If i use the non requestable prompt and insert it before the consent, using those functions
```
ctx.oidc.session.ensureClientContainer(clientId<string>)
ctx.oidc.session.promptedScopesFor(clientId<string>, scopes<Set|Array>
```
This will still set the scopes for the checks in the consent prompt right?

**Comment by panva** [comment] 2019-07-15 18:40
Yeah.

**Closed by panva** 2019-07-15 18:40 UTC
