### ISSUE TITLE
cannot catch error 

### ISSUE THREAD

**Issue by acodercat** [panva/node-oidc-provider#333] opened 2018-07-30 10:13 UTC
**Describe the bug**
https://github.com/panva/node-oidc-provider/blob/master/example/index.js#L65

here code cannot catch error

**Comment by panva** [comment] 2018-07-30 10:22
Based off this description i find it impossible to help you. You’re linking an example, that example works as intended, no bug to be seen. 

It seems you’re resolving to opening issues before troubleshooting or trying to understand the code or examples yourself. Please refrain from doing so again.

**Closed by panva** 2018-07-30 10:22 UTC

**Comment by acodercat** [comment] 2018-07-30 10:34
https://github.com/panva/node-oidc-provider/blob/master/example/index.js#L63
I tried it.

the middleware not run
```js
  router.use(async (ctx, next) => {
    console.log('the middleware not run');
    try {
      await next();
    } catch (err) {
      if (err instanceof SessionNotFound) {
        ctx.status = err.status;
        const { message: error, error_description } = err; // eslint-disable-line camelcase
        renderError(ctx, { error, error_description }, err);
      } else {
        throw err;
      }
    }
  });
```

**Comment by panva** [comment] 2018-07-30 10:38
router.use? This is not provider middleware. Its for the router and its actions only.

**Comment by acodercat** [comment] 2018-07-30 10:43
i want catch error
That's not good.
```js
provider.use(async (ctx, next) => {
  await next();
  // use anything from context to target the response to check it's an error
  if (ctx.body && ctx.body.error) {
    // ctx.body.error_description = '...';
    // ctx.body.error_uri = '...';
  }
});
```

**Comment by panva** [comment] 2018-07-30 10:47
There's no throwing from `await next()` in oidc-provider, all errors are handled to return valid codes and responses (even uncaughts).

Hence this:

> use anything from context to target the response to check it's an error.

**Comment by acodercat** [comment] 2018-07-30 10:51
That is, I can't get the error?

**Comment by acodercat** [comment] 2018-07-30 10:51
thanks

**Comment by acodercat** [comment] 2018-07-30 10:53
i see https://github.com/panva/node-oidc-provider/issues/317   You can mention it in this.

**Comment by acodercat** [comment] 2018-07-30 11:13
please
