### ISSUE TITLE
Error invalid grant on enabling Redis adapter

### ISSUE THREAD

**Issue by stefdaems** [panva/node-oidc-provider#529] opened 2019-09-10 13:06 UTC
**Describe the bug**
Before everything was working using the in memory adapter. Now I've implemented the redisAdapter as per example, I do receive errors on targeting the /token endpoint.

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
// provider configuration
As in your examples

// client(s) configuration
{
    client_id: 'yyyy_app',
    client_secret: 'xxxxxx,
    grant_types: ['authorization_code'],
    response_types: ['code'],
    redirect_uris: ["https://openidconnect.net/callback"],
    token_endpoint_auth_method: 'client_secret_basic'
}

```

Steps to reproduce the behaviour:

1.  authorize correctly
2. send token to /token endpoint
 

**Expected behaviour**
tokens are retrieved

**Environment:**
 - oidc-provider version: v6.6.2
 - node version: v12.10.0

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Logs**
```
2019-09-10T12:56:30.457Z oidc-provider:token accepted uid=ZvvbXPZBBGbUuJGH99rpe Params { grant_type: 'authorization_code', code: 'jDKNzxbWtKmuO8sNuzg0IvLfbO4Ip1Fx3tsTn4-_lF4', redirect_uri: 'https://openidconnect.net/callback', code_verifier: undefined, client_id: 'xxxxx', client_assertion: undefined, client_assertion_type: undefined, client_secret: 'yyyyyy' }
2019-09-10T12:56:30.457Z ioredis:redis write command[10.245.59.233:32379]: 0 -> hgetall([ 'oidc:AuthorizationCode:jDKNzxbWtKmuO8sNuzg0IvLfbO4Ip1Fx3tsTn4-_lF4' ])
2019-09-10T12:56:30.461Z ioredis:redis write command[10.245.59.233:32379]: 0 -> get([ 'oidc:uid:9nqc0cj7eQd8oET8NtgMq' ])
2019-09-10T12:56:30.462Z ioredis:redis write command[10.245.59.233:32379]: 0 -> get([ 'oidc:Session:ONXWB3Rhq2zh9AZEjGesL' ])
2019-09-10T12:56:30.464Z oidc-provider:mixin:is_session_bound not returning AuthorizationCode jDKNzxbWtKmuO8sNuzg0IvLfbO4Ip1Fx3tsTn4-_lF4 because it is session bound and token and session principal are now different
2019-09-10T12:56:30.465Z oidc-provider:error uid=ZvvbXPZBBGbUuJGH99rpe path=/token method=POST error={ error: 'invalid_grant', error_description: 'grant request is invalid' } detail=authorization code not found
```

**Comment by panva** [comment] 2019-09-10 13:20
Did you copy the redis adapter as-is or made changes? When i run the samples with the redis adapter i'm able to authenticate just fine.

**Comment by stefdaems** [comment] 2019-09-10 13:22
Hi, Thanks for the quick support. I've copied them as-is

**Comment by panva** [comment] 2019-09-10 13:27
I'm going to need more details as i cannot reproduce. "as in your examples" is not sufficient.

**Comment by panva** [comment] 2019-09-10 13:28
anyway,

> because it is session bound and token and session principal are now different

The Authorization Code is found but the session's account identifier that the code is bound to is not the same anymore.

**Comment by stefdaems** [comment] 2019-09-10 13:31
I've tested it using the https://openidconnect.net 
Redis adapter used:
`
const Redis = require('ioredis'); // eslint-disable-line import/no-unresolved
const isEmpty = require('lodash.isempty');

const client = new Redis(process.env.REDIS_URL, { keyPrefix: 'oidc:' });

const consumable = new Set([
  'AuthorizationCode',
  'RefreshToken',
  'DeviceCode',
]);

function grantKeyFor(id) {
    console.log(`grantKeyFor::id ${id}`)
  return `grant:${id}`;
}

function userCodeKeyFor(userCode) {
    console.log(`userCodeKeyFor::userCode ${userCode}`);
  return `userCode:${userCode}`;
}

function uidKeyFor(uid) {
    console.log(`uidKeyFor::userCode ${uidKeyFor}`);
  return `uid:${uid}`;
}

class RedisAdapter {
  constructor(name) {
    this.name = name;
  }

  async upsert(id, payload, expiresIn) {
    const key = this.key(id);
    const store = consumable.has(this.name)
      ? { payload: JSON.stringify(payload) } : JSON.stringify(payload);

    const multi = client.multi();
    multi[consumable.has(this.name) ? 'hmset' : 'set'](key, store);

    if (expiresIn) {
      multi.expire(key, expiresIn);
    }

    if (payload.grantId) {
      const grantKey = grantKeyFor(payload.grantId);
      multi.rpush(grantKey, key);
      // if you're seeing grant key lists growing out of acceptable proportions consider using LTRIM
      // here to trim the list to an appropriate length
      const ttl = await client.ttl(grantKey);
      if (expiresIn > ttl) {
        multi.expire(grantKey, expiresIn);
      }
    }

    if (payload.userCode) {
      const userCodeKey = userCodeKeyFor(payload.userCode);
      multi.set(userCodeKey, id);
      multi.expire(userCodeKey, expiresIn);
    }

    if (payload.uid) {
      const uidKey = uidKeyFor(payload.uid);
      multi.set(uidKey, id);
      multi.expire(uidKey, expiresIn);
    }

    await multi.exec();
  }

  async find(id) {
    const data = consumable.has(this.name)
      ? await client.hgetall(this.key(id))
      : await client.get(this.key(id));

    if (isEmpty(data)) {
      return undefined;
    }

    if (typeof data === 'string') {
      return JSON.parse(data);
    }
    const { payload, ...rest } = data;
    return {
      ...rest,
      ...JSON.parse(payload),
    };
  }

  async findByUid(uid) {
    const id = await client.get(uidKeyFor(uid));
    return this.find(id);
  }

  async findByUserCode(userCode) {
    const id = await client.get(userCodeKeyFor(userCode));
    return this.find(id);
  }

  async destroy(id) {
    const key = this.key(id);
    await client.del(key);
  }

  async revokeByGrantId(grantId) { // eslint-disable-line class-methods-use-this
    const multi = client.multi();
    const tokens = await client.lrange(grantKeyFor(grantId), 0, -1);
    tokens.forEach((token) => multi.del(token));
    multi.del(grantKeyFor(grantId));
    await multi.exec();
  }

  async consume(id) {
    await client.hset(this.key(id), 'consumed', Math.floor(Date.now() / 1000));
  }

  key(id) {
    return `${this.name}:${id}`;
  }
}

module.exports = RedisAdapter;
`

**Comment by panva** [comment] 2019-09-10 13:41
I am 100% certain the adapter sample works fine as i cannot reproduce the issue. Once more I ask for the rest of your configuration.

> "as in your examples" is not sufficient.

**Comment by stefdaems** [comment] 2019-09-10 13:44
Sorry, the configuration is here

```
{
    adapter: RedisAdapter,
    claims: {
        openid: ['sub'],
        email: ['email', 'email_verified'],
        profile: ['email', 'street', 'city']
    },
    features: {
        // disable the packaged interactions
        devInteractions: {
            enabled: false
        },
        encryption: {
            enabled: true
        },
        revocation: {
            enabled: true
        },
        introspection: {
            enabled: true
        },
    },
    routes: {
        authorization: '/authorize',
        check_session: '/session/check',
        code_verification: '/device',
        device_authorization: '/device/auth',
        end_session: '/session/end',
        introspection: '/token/introspection',
        jwks: '/jwks',
        registration: '/reg',
        request_object: '/request',
        revocation: '/token/revocation',
        token: '/token',
        userinfo: '/me'
    },
    jwks: {
        keys: [<my token>]
    },
    clients,
    findById: Account.findById,
    findAccount: Account.findAccount,
    async renderError(ctx, out, error) {
        ctx.type = 'html';
        ctx.body = `<!DOCTYPE html>
        <html>
          <head>
            <title>Redirect to wrong</title>
          </head>
          <body>
            <h3>Error</h3>
            ${JSON.stringify(error)}
          </body>
        </html>`;
    },
    cookies: {
        long: {
            signed: true,
            maxAge: (1 * 24 * 60 * 60) * 1000
        }, // 1 day in ms
        short: {
            signed: true
        },
        keys: ['tadaam']
    },
    formats: {
        AccessToken: 'jwt',
    },
```

**Comment by panva** [comment] 2019-09-10 13:45
What's your `findAccount`?

**Comment by panva** [comment] 2019-09-10 13:50
I’m thinking your accountId values may be integers. That could cause confusion. Throughout openid connect the sub claim, account id, whatever you call it - must be a string.

**Comment by stefdaems** [comment] 2019-09-10 13:53
The accountId doesn't contain integers, but mailaccounts. Maybe the @ signs can cause problems?

**Comment by panva** [comment] 2019-09-10 13:55
Nope, that’s not it. If its a string it works.

**Comment by panva** [comment] 2019-09-10 13:57
What's your `findAccount`?

**Comment by stefdaems** [comment] 2019-09-10 13:58
```
  static async findAccount(ctx, id, token) { // eslint-disable-line no-unused-vars
 (!store.get(id)) new Account(id); // eslint-disable-line no-new
    return store.get(id);
  }

  static async findById(ctx, id) {
    return new Account(id);
  }
````

**Comment by panva** [comment] 2019-09-10 14:01
@stefdaems these examples are not helping if I don't see the Account implementation.

Also note that `findById` is not used in v6.x anymore - which examples did you copy this from?

**Comment by stefdaems** [comment] 2019-09-10 14:02
https://github.com/panva/node-oidc-provider-example/blob/master/03-oidc-views-accounts/account.js

**Comment by stefdaems** [comment] 2019-09-10 14:10
This is the implementation of the Account
```
const _ = require('lodash');
const auth = require('./auth');
const fetch = require('node-fetch');
const {
  logger
} = require('`./logger');
const store = new Map();
const USERS = {
  '23121d3c-84df-44ac-b458-3d63a9a05497': {
    email: 'foo@example.com',
    email_verified: true,
  },
  'c2ac2b4a-2262-4e2f-847a-a40dd3c4dcd5': {
    email: 'bar@example.com',
    email_verified: false,
  },
  'xxx@yyy.be': {
    email: 'xxx@yyy.com',
    email_verified: false,
  },
};

class Account {
  constructor(id, profile) {
    this.accountId = id || nanoid();
    this.profile = profile;
    store.set(this.accountId, this);
  }

  // claims() should return or resolve with an object with claims that are mapped 1:1 to
  // what your OP supports, oidc-provider will cherry-pick the requested ones automatically
  claims() {
    logger.info(`Claims triggered`);
    console.log(`This accountId: ${JSON.stringify(this.accountId)}`);
    return Object.assign({}, USERS[this.accountId], {
      sub: this.accountId
    });
  }

  static async findAccount(ctx, id, token) { // eslint-disable-line no-unused-vars
    // token is a reference to the token used for which a given account is being loaded,
    //   it is undefined in scenarios where account claims are returned from authorization endpoint
    // ctx is the koa request context
    logger.info(`findAccount called with id: ${JSON.stringify(id)} and token: ${JSON.stringify(token)}`);
    console.log(`findAccount called with id: ${JSON.stringify(id)} and token: ${JSON.stringify(token)}`);
    if (!store.get(id)) new Account(id); // eslint-disable-line no-new
    return store.get(id);
  }

  static async authenticate(username, password) {
    try {
      const lowercased = String(username).toLowerCase();
      // const id = _.findKey(USERS, { username: lowercased });
      // this is usually a db lookup, so let's just wrap the thing in a promise
      const body = {
        type: 'user',
        username: username,
        password: password
      }
      logger.info(`fetching ${username} and ${password}`);
      console.log(`fetching ${username} and ${password}`);
      return fetch(process.env.AUTHENTICATE, {
          method: 'post',
          body: JSON.stringify(body),
          headers: {
            'Content-Type': 'application/json'
          }
        })
        .then((res) => {
          return res.json()
        })
        .then((user) => {
          if (user.success == true) {
            return new this(username);
          } else {
            return undefined
          }
        });
      return new this(id);
    } catch (err) {
      return undefined;
    }
  }
}

module.exports = Account;
```

**Comment by stefdaems** [comment] 2019-09-10 14:19
Can it be an issue if I don't add the accountId to the sub? like this

```
{
  "jti": "Evty7Nn0mGj6qcLfOIw0t",
  "sub": {
    "accountId": "xxx@yyy.com"
  },
  "iat": 1568108848,
  "exp": 1568112448,
  "scope": "openid email",
  "iss": "http://localhost:4444",
  "aud": "xxx_app"
}
```

But I do it like this

```
{
  "jti": "Evty7Nn0mGj6qcLfOIw0t",
  "sub": "xxx@yyy.com",
  "iat": 1568108848,
  "exp": 1568112448,
  "scope": "openid email",
  "iss": "http://localhost:4444",
  "aud": "xxx_app"
}
```

**Comment by panva** [comment] 2019-09-10 14:26
> Can it be an issue if I don't add the accountId to the sub? like this

That first sample's `sub` is completely wrong.

Using all the steps from https://github.com/panva/node-oidc-provider-example everything works fine. Hence i'm going to close this as not a bug, confirming the current label that the problem is your code/environment. Please retrace your steps and re-apply your changes in step by step manner.

I don't have the capacity to debug your code. My recommendation - implement proper accounts, not these in memory ones from the example and make small incremental changes.

**Closed by panva** 2019-09-10 14:26 UTC
Labels: environment setup problem, question

**Comment by stefdaems** [comment] 2019-09-10 14:29
Thanks for your support;

so this sub is fine 

```
{
  "jti": "Evty7Nn0mGj6qcLfOIw0t",
  "sub": "xxx@yyy.com",
  "iat": 1568108848,
  "exp": 1568112448,
  "scope": "openid email",
  "iss": "http://localhost:4444",
  "aud": "xxx_app"
}
```

**Comment by stefdaems** [comment] 2019-09-10 18:04
Fixed

```
return new this(username);
```

Caused to account object to be filled up with another accountId object. This made the structure go nuts.
