### ISSUE TITLE
Custom error handler

### ISSUE THREAD

**Issue by karlbateman** [panva/node-oidc-provider#70] opened 2017-01-19 18:04 UTC
Hey @panva,

Quick question, is it possible to implement custom error handling logic?

So that the following would be respected.. **note** I know this wouldn't work as your callback responds, but it can be visualised.

```javascript
app.use(oidc.callback)
app.use((err, req, res, next) => {...})
```

Would be real nice to render custom error pages and return custom JSON responses when things go bad.

**Comment by panva** [comment] 2017-01-19 18:20
Hey @karlbateman, sorry, this is probably not possible in the way you imagine - once oidc-providers gets a hold of the request it will respond to it in the way defined by OpenID Connect, there's not really much room for customization there, to be honest.

However, you may have noticed sometimes you get a html "oops, somethign went wrong" when oidc-provider responds to a browser and not a backend client making the request. It uses a helper function which you can [configure](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/defaults.js#L263-L283). This is used in the libraries two error handlers (regular api, and authorization) - [1](https://github.com/panva/node-oidc-provider/blob/master/lib/shared/authorization_error_handler.js#L56), [2](https://github.com/panva/node-oidc-provider/blob/master/lib/shared/error_handler.js#L34-L37). You must understand the purpose of that helper is to mainly make the rendered authorization errors look like the rest of your OP, not to change the responses.

**Comment by karlbateman** [comment] 2017-01-19 18:22
I understand, at least there is some flexibility available. Thanks for the quick response :+1:

**Comment by karlbateman** [comment] 2017-01-19 18:26
Would be great to be able to pass that to a template render :bulb:

**Comment by panva** [comment] 2017-01-19 18:32
In a standard OP interaction the end-user will never see these ;) These request usually tend to come up only during testing/development when you encounter them often, but frankly - errors during authorization are either rendered because they are absolutely critical (like not whitelisted redirect_uri or missing mandatory param), at that point the problem is likely elsewhere and all you really need is one user giving you a screencap of what the error is (or logging it yourself via events), regardless of what it looks like. Regular errors for valid clients and redirect_uris end up being forwarded to the RP anyway.

As the OP is completely unaware of what "upstream" is, what "template engine" could be there, i don't see how i can provide more than the helper that gets the context and error. If inside you render and assign it to this.body, is entirely up to you.

**Comment by karlbateman** [comment] 2017-01-19 18:36
I see, that was informative. Thanks for clearing that up :smile:

**Comment by karlbateman** [comment] 2017-01-19 18:38
Feel free to close

**Comment by karlbateman** [comment] 2017-01-19 18:41
I would love to see an introductory document which provides some examples of how such a mechanism works, typical user flow and it's benefits. Would help an absolute beginner get started easier with something like this..

Thanks for all your help @panva

**Closed** 2017-01-19 18:41 UTC

**Comment by panva** [comment] 2017-01-19 18:55
Well any documentation produced for a specific library can only be a subset of what's already linked to and well documents the various behaviors - [Core 1.0 documentation](http://openid.net/specs/openid-connect-core-1_0.html), and also, written from the RP's perspective [Basic Client Implementer's Guide 1.0](https://openid.net/specs/openid-connect-basic-1_0.html).

At least a rudimentary understanding openid connect, of what the OP does and how does it handle which errors, mainly their propagation to the RP is to be expected when being already so far as to setting up an OpenID Connect provider.

One is usually familiar with being at least an RP, so expecting those errors to be forwarded as part of the oauth dance shouldn't come as a surprise.

**Comment by karlbateman** [comment] 2017-01-19 19:16
Thanks for the info, I certainly need to read more about this approach.

**Comment by slavab89** [comment] 2017-06-19 14:02
In the `renderError` function that should return some HTML its also possible to redirect the user to some different page that will show something else using `this.redirect('/error')`

Also, regarding error handling, when reaching an invalid route it will throw a `invalid_request` and emit an event for this (not documented in `events.md`). I think that a more general question might have been to allow whoever uses the OP to put his own error handler in case of a "general error"?
Meaning that if for example i would like to add some additional data to the response body or change the format of how the error is returned (Simple text instead of JSON)..
