### ISSUE TITLE
OiDC Session maintaince

### ISSUE THREAD

**Issue by SSKasture** [panva/node-oidc-provider#387] opened 2018-10-26 14:00 UTC
Interaction/Session getting lost after we redirect to our identity provider.

```
app.post('/interaction/:grant/submit', parse, (req, res, next) => {
	console.log("inside submit");
	console.log(req);
    Account.authenticate(req.body.login, req.body.password)
	//Account.authenticate(req.body)
      .then(account => oidc.interactionFinished
	  (req, res, {	
       
       login: {
          account: account.accountId,
          remember: !!req.body.remember,
          ts: Math.floor(Date.now() / 1000),
        },
        consent: {
          rejectedScopes: req.body.remember ? [] : ['offline_access'],
        },
		
      })).catch(next);
	  
	  
  });
 
 app.get('/interaction/:grant', async (req, res) => {
	 console.log(req);
	 testGrant= req.params.grant;
    oidc.interactionDetails(req).then((details) => {
		console.log(details);
    res.redirect("*************&redirect_uri=http://localhost:3000/code");
    });
  });
```

Steps to reproduce the behaviour:

1.  User get redirected to Login page hosted by our IDP server
2.  Idp return response with authentication to app.post('/interaction/:grant/submit' during this step we are  loosing Session/Interaction
3.  we are getting error Invalid Session
```
SessionNotFound: invalid_request
    at Provider.getInteraction (C:\Users\SKasture\Documents\GitHub\oidc provider\node_modules\oidc-provider\lib\provider.js:63:11)
    at Provider.interactionResult (C:\Users\SKasture\Documents\GitHub\oidc provider\node_modules\oidc-provider\lib\provider.js:210:46)
    at Provider.interactionFinished (C:\Users\SKasture\Documents\GitHub\oidc provider\node_modules\oidc-provider\lib\provider.js:222:33)
    at Account.authenticate.then.account (C:\Users\SKasture\Documents\GitHub\oidc provider\index.js:81:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

Provider should not maintain state at all and redirect user always to authenticate.

**Environment:**
 - oidc-provider version: [e.g. v4.3.0]
 - node version: [e.g. v8.9.0]

**Comment by panva** [comment] 2018-10-26 14:14
Can you post a full example app to verify your setup? Strip the adapter logic, just the provider app and your interactions. Thanks.

**Comment by SSKasture** [comment] 2018-10-26 14:28
This  is my complete code
const express = require('express');
const Provider = require('oidc-provider');
const Account = require('./account');
const bodyParser = require('body-parser');
const Clever = require('clever');
const request = require('request-promise');
const app = express();
const parse = bodyParser.urlencoded({ extended: false });

let testGrant=null;

const clients = [{
    client_id: 'test_implicit_app',
    grant_types: ['implicit'],
    response_types: ['id_token'],
    redirect_uris: ['https://testapp/signin-oidc'],
    token_endpoint_auth_method: 'none'
},
{
    client_id: 'test_oauth_app',
    client_secret: 'super_secret',
    grant_types: ['client_credentials'],
    redirect_uris: [],
    response_types: [],
}];

const oidc = new Provider('http://localhost:3000', {
    claims: {
        address: ['address'],
        email: ['email', 'email_verified'],
        phone: ['phone_number', 'phone_number_verified'],
        profile: ['birthdate', 'family_name', 'gender', 'given_name', 'locale', 'middle_name', 'name',
            'nickname', 'picture', 'preferred_username', 'profile', 'updated_at', 'website', 'zoneinfo']
    },
    scopes: ['api1'],
    features: {
        clientCredentials: true,
        introspection: true,
        sessionManagement: true,
		
    },
	
    findById: Account.findById,
});
app.post('/interaction/:grant/submit', parse, (req, res, next) => {
	console.log("inside submit");
	console.log(req);
    Account.authenticate(req.body.login, req.body.password)
	//Account.authenticate(req.body)
      .then(account => oidc.interactionFinished
	  (req, res, {	
       
       login: {
          account: account.accountId,
          remember: !!req.body.remember,
          ts: Math.floor(Date.now() / 1000),
        },
        consent: {
          rejectedScopes: req.body.remember ? ['offline_access'] : [],
        },
		
      })).catch(next);
	  
	  
  });
 
 app.get('/interaction/:grant', async (req, res) => {
	 console.log(req);
	 testGrant= req.params.grant;
    oidc.interactionDetails(req).then((details) => {
		console.log(details);
    res.redirect("http://localhost:8080/idp");
    });
  });

**Comment by panva** [comment] 2018-10-26 14:30
>     res.redirect("http://localhost:8080/idp");

this?

**Comment by SSKasture** [comment] 2018-10-26 14:31
That is my application which actually authenticates user login

**Comment by panva** [comment] 2018-10-26 14:33
and it makes the user-agent post username and password to `/interaction/:grant/submit`?

**Comment by SSKasture** [comment] 2018-10-26 14:33
Yes

**Comment by panva** [comment] 2018-10-26 14:39
A hunch tells me thats not true and its a backend call instead. 

Can you show me the html it renders to the user. One with the form that posts to the interaction submit route

**Comment by SSKasture** [comment] 2018-10-26 14:41
It's complete different application which do user authentication and send response back to provider

**Comment by panva** [comment] 2018-10-26 14:42
Can you show me the html it renders with the form that posts to the interaction submit route?

**Comment by panva** [comment] 2018-10-29 07:48
Gave this a thought and i’m certain you’re not using the library as intended. If you would, provide a stripped down running example exhibiting your problem. Thank you.

**Comment by panva** [comment] 2018-10-29 07:49
I’m closing this but feel free to post if you wish to get help.

**Closed by panva** 2018-10-29 07:49 UTC
Labels: environment setup problem, question, waiting for feedback
