### ISSUE TITLE
create jwt access_token instead of opaque tokens

### ISSUE THREAD

**Issue by adnan-kamili** [panva/node-oidc-provider#127] opened 2017-07-04 13:33 UTC
Is there any support for creating jwt access_tokens, other oidc implementations do allow that

**Comment by panva** [comment] 2017-07-04 13:59
duplicate of #93. oidc-provider will stick with an opaque Bearer token format

**Closed** 2017-07-05 07:49 UTC

**Comment by panva** [comment] 2018-06-16 13:56
#294 introduces the option to have any token returned to an RP as a JWT. Calling for comments and reviews.
